src/main/java/ua/proba/model/Contact.java
package ua.proba.model;

import javax.persistence.*;

/**
 * Created by yuri on 30.06.2016.
 */
@Entity
public class Contact {

    @Id
    @GeneratedValue
    private int id;
    @Column(nullable = false)
    private String sku;
    @Column(nullable = true)
    private String price;
    @Column(nullable = true)
    private String qty;
    @Column(nullable = true)
    private String title;
    @Column(nullable = true)
    private String item_length;
    @Column(nullable = true)
    private String item_width;
    @Column(nullable = true)
    private String item_height;
    @Column(nullable = true)
    private String item_weight;
    @Column(nullable = true)
    private String upc;
    @Column(nullable = true)
    private String ups_bool;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getQty() {
        return qty;
    }

    public void setQty(String qty) {
        this.qty = qty;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getItem_length() {
        return item_length;
    }

    public void setItem_length(String item_length) {
        this.item_length = item_length;
    }

    public String getItem_width() {
        return item_width;
    }

    public void setItem_width(String item_width) {
        this.item_width = item_width;
    }

    public String getItem_height() {
        return item_height;
    }

    public void setItem_height(String item_height) {
        this.item_height = item_height;
    }

    public String getItem_weight() {
        return item_weight;
    }

    public void setItem_weight(String item_weight) {
        this.item_weight = item_weight;
    }

    public String getUpc() {
        return upc;
    }

    public void setUpc(String upc) {
        this.upc = upc;
    }

    public String getUps_bool() {
        return ups_bool;
    }

    public void setUps_bool(String ups_bool) {
        this.ups_bool = ups_bool;
    }

    //    @Id
//    @GeneratedValue
//    private int id;
//    private String sku;
//    private Float price;
//    private Integer qty;
//    private String title;
//    private Float item_length;
//    private Float item_width;
//    private Float item_height;
//    private Float item_weight;
//    private String upc;
//    private Boolean ups_bool;
//
//    public int getId() {
//        return id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
//
//    public String getSku() {
//        return sku;
//    }
//
//    public void setSku(String sku) {
//        this.sku = sku;
//    }
//
//    public Float getPrice() {
//        return price;
//    }
//
//    public void setPrice(Float price) {
//        this.price = price;
//    }
//
//    public Integer getQty() {
//        return qty;
//    }
//
//    public void setQty(Integer qty) {
//        this.qty = qty;
//    }
//
//    public String getTitle() {
//        return title;
//    }
//
//    public void setTitle(String title) {
//        this.title = title;
//    }
//
//    public Float getItem_length() {
//        return item_length;
//    }
//
//    public void setItem_length(Float item_length) {
//        this.item_length = item_length;
//    }
//
//    public Float getItem_width() {
//        return item_width;
//    }
//
//    public void setItem_width(Float item_width) {
//        this.item_width = item_width;
//    }
//
//    public Float getItem_height() {
//        return item_height;
//    }
//
//    public void setItem_height(Float item_height) {
//        this.item_height = item_height;
//    }
//
//    public Float getItem_weight() {
//        return item_weight;
//    }
//
//    public void setItem_weight(Float item_weight) {
//        this.item_weight = item_weight;
//    }
//
//    public String getUpc() {
//        return upc;
//    }
//
//    public void setUpc(String upc) {
//        this.upc = upc;
//    }
//
//    public Boolean getUps_bool() {
//        return ups_bool;
//    }
//
//    public void setUps_bool(Boolean ups_bool) {
//        this.ups_bool = ups_bool;
//    }
//
//    @Override
//    public boolean equals(Object obj) {
//        try { return sku.equals(((Contact) obj).getSku()); }
//        catch (Exception exc) { return false; }
//    }
//    @Override
//    public int hashCode() {
//        return 31 + ((sku == null) ? 0 : sku.hashCode());
//    }


}

src/main/java/ua/proba/action/BaseActionBean.java
package ua.proba.action;

import net.sourceforge.stripes.action.*;
import ua.proba.dao.ContactDao;
import ua.proba.dao.ContactDaoImpl;
import ua.proba.model.Contact;

import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by yuri on 30.06.2016.
 */
public abstract class BaseActionBean implements ActionBean {
    private ActionBeanContext actionBeanContext;

    public ActionBeanContext getContext() {
        return actionBeanContext;
    }

    public void setContext(ActionBeanContext actionBeanContext) {
        this.actionBeanContext = actionBeanContext;
    }


}

src/main/java/ua/proba/action/ContactListActionBean.java
package ua.proba.action;

import net.sourceforge.stripes.action.*;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import ua.proba.dao.ContactDao;
import ua.proba.dao.ContactDaoImpl;
import ua.proba.hibernate.util.HibernateUtil;
import ua.proba.model.Contact;

import java.io.*;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

/**
 * Created by yuri on 30.06.2016.
 */

public class ContactListActionBean extends BaseActionBean {
    private static final String LIST = "contact_list.jsp";
    private final static String FORM = "contact_form.jsp";
    private final static String DISPLAY = "/ContactList.action?contact=";
    ContactDao contactDao = new ContactDaoImpl();

    private Contact contactId;
    private Contact contact;

    public Contact getContact() {
        return contact;
    }

    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Contact getContactId() {
        return contactId;
    }

    public void setContactId(Contact contactId) {
        this.contactId = contactId;
    }

    @DefaultHandler
    public Resolution list() {
        return new ForwardResolution(LIST);
    }

    public Resolution delete() {
          contactDao.delete(contactId.getId());
        return new RedirectResolution(DISPLAY);
    }

    public Resolution edit() {
        contactId = contactDao.getSku(contactId.getSku());
        return new ForwardResolution(FORM);
    }

    public List<Contact> getContacts() {
        return contactDao.read();
    }

    public Resolution save() {
        contactId = contactDao.getSku(contactId.getSku());
        contactDao.edit(contactId);
        //return new RedirectResolution(DISPLAY);
        getContext().getResponse().setHeader("X-Stripes-Success","true");
        return new ForwardResolution(LIST);
    }
//    public Resolution cancel() {
//        return new ForwardResolution(DISPLAY);
//    }

}

src/main/java/ua/proba/action/FileUploadActionBean.java
package ua.proba.action;

import net.sourceforge.stripes.action.*;
import org.apache.commons.collections.map.HashedMap;
import org.apache.commons.io.Charsets;
import org.apache.commons.io.IOUtils;
import org.apache.commons.io.LineIterator;
import org.apache.commons.lang.ObjectUtils;
import ua.proba.dao.ContactDao;
import ua.proba.dao.ContactDaoImpl;
import ua.proba.model.Contact;

import java.io.*;
import java.util.*;

/**
 * Created by yuri on 01.07.2016.
 */

public class FileUploadActionBean extends BaseActionBean {

    private FileBean fileToUpload;
    private String message;
    private String message2;
    BufferedReader br = null;
    String line = "";
    String cvsSplitBy = "\",\"";


    Set<Contact> contactsi = new HashSet<Contact>();
    ContactDao contactDao = new ContactDaoImpl();



    private Contact contactId;

    public Contact getContactId() {
        return contactId;
    }

    public void setContactId(Contact contactId) {
        this.contactId = contactId;
    }

    public String getMessage2() {
        return message2;
    }

    public void setMessage2(String message2) {
        this.message2 = message2;
    }

    @DefaultHandler
    public Resolution index() {
        return new ForwardResolution("file_to_upload.jsp");

    }

    @HandlesEvent("upload")
    public Resolution upload() throws IOException {
        String saveToLocation = fileToUpload.getFileName();
        fileToUpload.save(new File(saveToLocation));
        message = "File uploaded to " + saveToLocation;
        br = new BufferedReader (new InputStreamReader(new FileInputStream(saveToLocation)));
        //br = new LineNumberReader(new FileReader(saveToLocation));
        while ((line = br.readLine()) != null) {
            try {
                String[] country = line.replaceAll("NULL", "\"NULL\"").split(cvsSplitBy);
                Contact con = new Contact();
                con.setSku(country[0].replaceAll("\"", ""));
                con.setPrice(country[1]);
                con.setQty(country[2]);
                con.setTitle(country[3]);
                con.setItem_length(country[4]);
                con.setItem_weight(country[5]);
                con.setItem_height(country[6]);
                con.setItem_width(country[7]);
                con.setUpc(country[8]);
                con.setUps_bool(country[9].replaceAll("\"", ""));
                contactsi.add(con);
            }catch (ArrayIndexOutOfBoundsException e){
                System.out.println(e);
            }
       }

        Iterator<Contact> itr =contactsi.iterator();
        while(itr.hasNext()) {

            contactDao.save(itr.next());
        }
        fileToUpload.delete();

        return this.index();
    }



    public FileBean getFileToUpload() {
        return fileToUpload;
    }

    public void setFileToUpload(FileBean fileToUpload) {
        this.fileToUpload = fileToUpload;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}

src/main/webapp/contact_form.jsp
<%--
  Created by IntelliJ IDEA.
  User: yuri
  Date: 30.06.2016
  Time: 17:29
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="/common/taglibs.jsp"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>${title}</title><!-- (1) -->
    <link rel="stylesheet" type="text/css"
          href="${contextPath}/css/style.css"><!-- (2) -->
    <script src="${contextPath}/js/prototype.js"
            type="text/javascript"></script>
    <script type="text/javascript"
            src="${contextPath}/js/jquery.js"></script>
    <script type="text/javascript" src="${contextPath}/js/contact_form.js">
    </script>
    <script type="text/javascript" src="${contextPath}/js/contact_list.js">
    </script>
</head>
<body>

<s:form id="form" action="/ContactList.action">
    <div><s:hidden name="contactId.sku"/></div>
<table class="form">
    <%--<tr>--%>
        <%--<td>sku:</td>--%>
        <%--<td><s:text name="contactId.sku" /></td><!-- (2) -->--%>
    <%--</tr>--%>
    <tr>
        <td>Price:</td>
        <td><s:text name="contactId.price"/></td><!-- (2) -->
    </tr>
    <tr>
        <td>Qty:</td>
        <td><s:text name="contactId.qty"/></td>
    </tr>
    <tr>
        <td>Title:</td>
        <td><s:text name="contactId.title"/></td>
    </tr>
    <tr>
        <td>Item length:</td>
        <td><s:text name="contactId.item_length"/></td>
    </tr>
    <tr>
        <td>Item width:</td>
        <td><s:text name="contactId.item_width"/></td>
    </tr>
    <tr>
        <td>Item height:</td>
        <td><s:text name="contactId.item_height"/></td>
    </tr>
    <tr>
        <td>Item weigh:</td>
        <td><s:text name="contactId.item_weight"/></td>
    </tr>
    <tr>
        <td>UPC:</td>
        <td><s:text name="contactId.upc"/></td>
    </tr>
    <tr>
        <td>UPS Bool:</td>
        <td><s:text name="contactId.ups_bool"/></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <s:submit name="save" value="Save" onclick="return submitForm(this);"/><!-- (3) -->
            <s:submit name="cancel" value="Cancel" onclick="$('#contact_form').hide();"/>
        </td>
    </tr>
</table>
</s:form>

</body>
</html>

src/main/webapp/contact_list.jsp
<%@include file="/common/taglibs.jsp"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>${title}</title><!-- (1) -->
    <link rel="stylesheet" type="text/css"
          href="${contextPath}/css/style.css"><!-- (2) -->
    <script src="${contextPath}/js/prototype.js"
            type="text/javascript"></script>
    <script type="text/javascript"
            src="${contextPath}/js/jquery.js"></script>
    <script type="text/javascript" src="${contextPath}/js/contact_form.js">
    </script>
    <script type="text/javascript" src="${contextPath}/js/contact_list.js">
    </script>
</head>
<body>
<table class="borderAll">
    <div id="contact_list">
        </div>
            <s:link beanclass="ua.proba.action.FileUploadActionBean">Upload file</s:link>
            <br/>
            <d:table name="${actionBean.contacts}" id="contact" requestURI=""
                     defaultsort="1">
                <d:column title="sku" property="sku"
                          sortable="true"/>
                <d:column title="Price" property="price"
                          sortable="true"/>
                <d:column title="Qty" property="qty" sortable="true"/>
                <d:column title="Title" property="title" sortable="true"/>
                <d:column title="Item length" property="item_length" sortable="true"/>
                <d:column title="Item width" property="item_width" sortable="true"/>
                <d:column title="Item height" property="item_height" sortable="true"/>
                <d:column title="Item weight" property="item_weight" sortable="true"/>
                <d:column title="UPC" property="upc" sortable="true"/>
                <d:column title="UPS Bool" property="ups_bool" sortable="true"/>

                <d:column title="Action">

                    <s:link beanclass="ua.proba.action.ContactListActionBean"
                            event="edit" onclick="return ajaxLink(this, '#contact_form');">
                        <%--<s:param name="contactId.id" value="${contact.id}"/>--%>
                        <s:param name="contactId.sku" value="${contact.sku}" />
                        Edit
                    </s:link> |
                    <s:link beanclass="ua.proba.action.ContactListActionBean" event="delete"
                            onclick="return ajaxLink(this, '#contact_list');">
                        <s:param name="contactId.id" value="${contact.id}"/>Delete</s:link>

                </d:column>
            </d:table>
            <br/>
            <br/>



    <div id="contact_form"></div>
</table>
</body>
</html>

src/main/webapp/file_to_upload.jsp
<%--
  Created by IntelliJ IDEA.
  User: yuri
  Date: 01.07.2016
  Time: 23:21
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="/common/taglibs.jsp"%>
<html>
<head>
    <title>Title</title>
    <script src="${contextPath}/js/prototype.js"
            type="text/javascript"></script>
    <script type="text/javascript"
            src="${contextPath}/js/jquery.js"></script>
    <script type="text/javascript" src="${contextPath}/js/contact_form.js">
    </script>
    <script type="text/javascript" src="${contextPath}/js/contact_list.js">
    </script>
</head>
<body>
${actionBean.message2}
<s:form action="${pageContext.request.contextPath}">
    <s:file name="fileToUpload" />
    <br/><br/>
    <s:submit name="upload" value="upload"/>
</s:form>
<br/>
${actionBean.message}
<br/>
<s:link beanclass="ua.proba.action.ContactListActionBean">Back main</s:link>
</body>
</html>

src/main/webapp/index.jsp
<%--
  Created by IntelliJ IDEA.
  User: yuri
  Date: 29.06.2016
  Time: 22:03
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<jsp:forward page="/ContactList.action"/>